version: "3.7"
services:
  api:
    image: "marquezproject/marquez:${TAG}"
    # platform: linux/amd64
    container_name: marquez-api
    environment:
      - MARQUEZ_CONFIG=/usr/src/app/marquez.dev.yml
      - MARQUEZ_PORT=${API_PORT}
      - MARQUEZ_ADMIN_PORT=${API_ADMIN_PORT}
      - POSTGRES_HOST=db
      - SEARCH_ENABLED=${SEARCH_ENABLED}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_ADMIN_PORT}:${API_ADMIN_PORT}"
    volumes:
      - data:/opt/marquez
    links:
      - "db:postgres"
    depends_on:
      - db
      - log-db
    entrypoint: ["/opt/marquez/wait-for-it.sh", "db:${POSTGRES_PORT}", "--", "./entrypoint.sh"]

  db:
    image: postgres:14
    container_name: marquez-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - db-conf:/etc/postgresql
      - db-init:/docker-entrypoint-initdb.d
      - db-backup:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]

  log-db:
    image: postgres:14
    container_name: marquez-log-db
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass
    ports:
      - "5433:5432"
    volumes:
      - log-db-data:/var/lib/postgresql/data
      - ./init-audit-log-db.sql:/docker-entrypoint-initdb.d/init-audit-log-db.sql

volumes:
  data:
  db-conf:
  db-init:
  db-backup:
  log-db-data: